### ISSUE TITLE
Installation as cargo dependency fails

### ISSUE THREAD

**Issue by iredelmeier** [aep/pug-rs#4]
Hi there!

It seems like installing the crate as a cargo dependency fails. I believe that this has something to do with the crate being available as a `cydlib`, although I'm not sure exactly. Oddly, cloning the repo and adding `pug-rs` as a path-based dependency doesn't cause the same problem - the `rlib` is correctly found then.

(This may instead be an upstream cargo and/or crates.io bug.)

**Comment by aep** [comment]
huh thats strange. whats the error message?

**Comment by iredelmeier** [comment]
Whoops, should've included that before...

```
error[E0463]: can't find crate for `pug`
 --> src/lib.rs:4:1
  |
4 | extern crate pug;
  | ^^^^^^^^^^^^^^^^^ can't find crate
```

As an experiment, I published [this branch](https://github.com/iredelmeier/pug-rs/tree/no-cdylib) that omits `cdylib`, and determined that depending on this version *does* work.

**Comment by aep** [comment]
huh that's strange. i can't reproduce it.
but i also published a new version with your other changes, according to your analysis there is a change it just works now

**Comment by iredelmeier** [comment]
Looks like the new version works correctly. Thanks!

Who knows what was up with the old one :)
